### ISSUE TITLE
python error

### ISSUE THREAD

**Issue by kromar** [kromar/blender_CollectionMaster#1]
"C:\Users\user\GIT_projects\blenderdevelopment\deployment\blender_addons\addons_contrib\addon_collectionmaster\__init__.py", line 210, in execute
self.exclude_viewport(self.item_excluded)
File "C:\Users\user\GIT_projects\blenderdevelopment\deployment\blender_addons\addons_contrib\addon_collectionmaster\__init__.py", line 271, in exclude_viewport
ob.hide_set(state)
RuntimeError: Error: Object 'mymesh' can't be hidden because it is not in View Layer 'Render Layer'!

**Comment by kromar** [comment]
location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "C:\Repo\BlenderDevelopment\development\src_28\addons_contrib\addon_collectionmaster\__init__.py", line 179, in execute
    ob.hide_set(self.status)
RuntimeError: Error: Object 'BL_Grid_offset_0.01_64' can't be hidden because it is not in View Layer 'RenderLayer'!


location: <unknown location>:-1
